Clean up image upload and retrieval logic inside of a program as an admin
novaforgood/RISC-Frontend pull request #100
Opened 2021-06-19 08:06 UTC by innopoop

Addresses #88 

Routes affected:
/program/[slug]/
/program/[slug]/settings

Changes:
1. Settings page icon upload & saving
2. Homepage image proper resizing
3. Homepage image proper upload
4. Homepage image proper retrieval and restoration of dimensions
5. Styling changes

2021-06-19 08:07 UTC, nova-admin commented
#### 📝Changed routes:


| [**/program/\[slug\]**](https://risc-lmhym6blq-novaforgood.vercel.app/program/[slug]) | [**/program/\[slug\]/settings**](https://risc-lmhym6blq-novaforgood.vercel.app/program/[slug]/settings) |
|:-:|:-:|
|<a href="https://risc-lmhym6blq-novaforgood.vercel.app/program/[slug]"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/NVqGx3h0hSU23dpf8aHAUsYvRnHJjZR6WnYZQGOIf07PN-TNhlL8A3CSmz4FKA7btGGTX66xoREGkg6DBAAU-w.png&w=600" alt="Screenshot of /program/[slug]" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xOa5h_jvQwTtKJJwbx7JFXFX8bN-1m0OhiAM_XVTJeg-w_NKqOVV27X5R53QAnim1Pw36PxzM3126yQhpfp9Fw.png">(view full size)</a> |<a href="https://risc-lmhym6blq-novaforgood.vercel.app/program/[slug]/settings"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ais2ZPREZQbxTn-ymixTFZx3IudDQYrr5_vmVzRBXVNmpmAw-XY5seU9NWXSSOumNumGqpv0n4w9cxPfDBSQow.png&w=600" alt="Screenshot of /program/[slug]/settings" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/ocoJ5qvcrB8NUfBg6Gzr8xsfU_4z5tRS14Jf2MW0m6T6PycG7QAb_8CqYgmGz_m5HsVfkfsp-1TU2KQoeZo19g.png">(view full size)</a> |







Commit a1ba467944ef05007c7ccce26c39b73cea4986d9 (https://risc-lmhym6blq-novaforgood.vercel.app).

2021-06-19 19:41 UTC, legitmaxwu commented
Good stuff! Icon upload works great, and I'll leave code comments later.

Comments on general functionality:

- Cannot edit homepage text (I type and nothing shows up)
- Image sizing should be more sensitive (I have to drag my cursor a lot just to change the image size a little)
- No point in having the drag handles on the middles of edges because you can't squash the image
- Adding an image does not count as editing the homepage (Publish button still disabled)

2021-06-19 19:44 UTC, legitmaxwu commented
![image](https://user-images.githubusercontent.com/19853022/122653788-f6becc00-d0fb-11eb-8132-0ee65fa57ecf.png)

Also, could you look into the dropdown image not changing on program icon change? (Should just be about adding a refetch or something)

2021-06-19 21:16 UTC, innopoop commented
> <img alt="" width="200px" src="https://user-images.githubusercontent.com/19853022/122653788-f6becc00-d0fb-11eb-8132-0ee65fa57ecf.png">
> 
> Also, could you look into the dropdown image not changing on program icon change? (Should just be about adding a refetch or something)

I looked into why the tab wasn't showing the correct program and it was weird because even though I refetched inside of the component, it was getting the wrong data altogether. I'm not sure if it has to do with the fact that Choose Tab Layout is only rendered once as a child of the page or something else.

2021-06-19 21:28 UTC, legitmaxwu commented
> > <img alt="" width="200px" src="https://user-images.githubusercontent.com/19853022/122653788-f6becc00-d0fb-11eb-8132-0ee65fa57ecf.png">
> > Also, could you look into the dropdown image not changing on program icon change? (Should just be about adding a refetch or something)
> 
> I looked into why the tab wasn't showing the correct program and it was weird because even though I refetched inside of the component, it was getting the wrong data altogether. I'm not sure if it has to do with the fact that Choose Tab Layout is only rendered once as a child of the page or something else.

Did you refetch getMyUser or getProgramBySlug?

2021-06-19 21:32 UTC, legitmaxwu requested changes
Editing works now! More functional comments:

- If I add an image, hitting publish does not save anything properly
- Adding an image still doesn't count as an "edit"

2021-06-20 02:36 UTC, innopoop commented
> > > <img alt="" width="200px" src="https://user-images.githubusercontent.com/19853022/122653788-f6becc00-d0fb-11eb-8132-0ee65fa57ecf.png">
> > > Also, could you look into the dropdown image not changing on program icon change? (Should just be about adding a refetch or something)
> > 
> > 
> > I looked into why the tab wasn't showing the correct program and it was weird because even though I refetched inside of the component, it was getting the wrong data altogether. I'm not sure if it has to do with the fact that Choose Tab Layout is only rendered once as a child of the page or something else.
> 
> Did you refetch getMyUser or getProgramBySlug?

I refetched both just to check, but I think you only need to refetch program correct? Perhaps refetching it inside of the ProgramDropdown component isn't the best idea. I will need to think about how to update the component a little more.

2021-06-22 04:00 UTC, legitmaxwu requested changes
I found the reason why it's not refetching--the imported refetch function from graphql.ts is not meant for direct calling, it's meant to be passed into the refetchQueries parameter in the useMutation hook.

If you would like to call refetch directly, you'd need to unpack the function from the useQuery hook. i.e. `const { data, refetch } = useQuery()`

See:
- https://www.apollographql.com/docs/react/data/queries/#refetching
- https://www.apollographql.com/docs/react/caching/advanced-topics/
- https://www.graphql-code-generator.com/docs/generated-config/typescript-react-apollo#withrefetchfn

2021-06-22 04:00 UTC, legitmaxwu commented on src/pages/program/[slug]/settings.tsx
> +                refetchGetMyUserQuery();
Delete this line

2021-06-22 04:00 UTC, legitmaxwu commented on src/pages/program/[slug]/settings.tsx
>    const [updateProgram] = useUpdateProgramMutation();
```
useUpdateProgramMutation({ refetchQueries: [ refetchGetMyUserQuery() ] });
```

2021-06-22 04:46 UTC, innopoop commented on src/pages/program/[slug]/settings.tsx
>    const [updateProgram] = useUpdateProgramMutation();
brain is yuge

2021-06-27 20:19 UTC, legitmaxwu approved these changes

2021-06-27 20:20 UTC, merged