P0 bug fixes
novaforgood/RISC-Frontend pull request #138
Opened 2021-07-09 08:25 UTC by innopoop

Show admins in settings page
Remove double click to access program homepage from user homepage
Correct functionality of /apply page back button

2021-07-11 04:18 UTC, nova-admin commented
#### 📝Changed routes:


| [**/create**](https://risc-ufo5vs050-novaforgood.vercel.app/create) | [**/**](https://risc-ufo5vs050-novaforgood.vercel.app/) |
|:-:|:-:|
|<a href="https://risc-ufo5vs050-novaforgood.vercel.app/create"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/mu1imLE8q0QPI4pGaRMOKOUVEecksf-6MzXLoZEFBJA0IkzSR0cg2M9qacGuSCz72fEDSEIhZsptEPLEenIDjg.png&w=600" alt="Screenshot of /create" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/zDfSvVmO-twffLVN50RW3VIHqRFfKLEXLleDJ8gBDaEMhAahnieVRFhuzU-A0JSQRdpK779SLm9qRYlsRLiHBg.png">(view full size)</a> |<a href="https://risc-ufo5vs050-novaforgood.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/ELriN2Ca3opiUGcZSSsxKwxojd3T3dp_7sHVQsWUpWz-wRXLNLzQzUNVVlWDTp9-ySntjgqxOVBfh-IwP--E8w.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/rkPD8jhi01ALgXkPVLsq_yLizIUNxUAE__UVIluH1bj3WZi-QItFQ1efNQydba7w7Hx23rp6BxIwQ85TOrHX_Q.png">(view full size)</a> |



| [**/login**](https://risc-ufo5vs050-novaforgood.vercel.app/login) | [**/program/\[slug\]/apply**](https://risc-ufo5vs050-novaforgood.vercel.app/program/[slug]/apply) |
|:-:|:-:|
|<a href="https://risc-ufo5vs050-novaforgood.vercel.app/login"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/wJFUoPNw9vOE7LVg5M79PqA1mNbBmOIbmYskFJGveTKR-7Aw3amkVGaQ22oRjo99L5C8_6ZCJ6oTMvFT1Zp-1w.png&w=600" alt="Screenshot of /login" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/UfpdZ2AELoYcqvOAi8Fh-szgIJxyRybu22k9mAxj37XqhDMzRtqwcndwoH1JANtWTYEraj3MkNx_RAL0aPAltA.png">(view full size)</a> |<a href="https://risc-ufo5vs050-novaforgood.vercel.app/program/[slug]/apply"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/tTpuNsZsgnLObiqen3qtkkD1DiRVboHv-XTGdGjhLMNXwfya-BfwTvr4sE_b_3ZdX0JSGZHrb3h4gFDGBTYK8A.png&w=600" alt="Screenshot of /program/[slug]/apply" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/yUBSwZakqDdAtOiIJ44tEiZm_npYj6fkzELyoRl-FuTj64Y9GWU-iaMedcaaip1X-9uyxXoWlCCREIrfaqADGw.png">(view full size)</a> |



| [**/program/\[slug\]/settings**](https://risc-ufo5vs050-novaforgood.vercel.app/program/[slug]/settings) | [**/signup**](https://risc-ufo5vs050-novaforgood.vercel.app/signup) |
|:-:|:-:|
|<a href="https://risc-ufo5vs050-novaforgood.vercel.app/program/[slug]/settings"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/1VPDxJj-jSFUSJHlbtgJPzeO_ss1Hc8AnKbEL28sm_h2sw9NCJXZpwvEnRAByRtUMmBNsTiIM9zPF2-cFvhJmQ.png&w=600" alt="Screenshot of /program/[slug]/settings" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/HcNiQSxX7Kywya6yIVplB6jLjakYJKp57CnmAzWR9OycOgSVANtmPGCZdW6ENPbEPy7Sq_5zNvUZJI-KuRv3Gg.png">(view full size)</a> |<a href="https://risc-ufo5vs050-novaforgood.vercel.app/signup"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/_3DEO6Hzgc7Uw4WRnDlQ7gHli77olU40gkn3VgHpPVeI_P9lwsvfCGj2hSSQO68fOduTM9kHcwigM8LvQcmsYA.png&w=600" alt="Screenshot of /signup" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/vuL0GtJugKuvBdxu8qSOfwH8ChepaMlPBg8YKuYg7G6iZM0f3H1hS9ztLGIZ7jwk9hkZ5RqE9bSXvdDtgrfO9Q.png">(view full size)</a> |



And 1 other route:
- [**/verify**](https://risc-ufo5vs050-novaforgood.vercel.app/verify)



Commit 2377c6487ec161561f34f731b3fa791752c5d2ea (https://risc-ufo5vs050-novaforgood.vercel.app).

2021-07-13 02:08 UTC, legitmaxwu approved these changes
LGTM. For copying links, is it possible to auto-highlight the selected text when you click copy? Otherwise, there's no clear indication that the copy went through.

2021-07-13 02:11 UTC, legitmaxwu requested changes

2021-07-13 02:11 UTC, legitmaxwu commented on src/components/ProfileModal.tsx
> -            <BookAChat mentor={profile} />
Why is this removed?

2021-07-13 02:17 UTC, legitmaxwu requested changes

2021-07-13 02:17 UTC, legitmaxwu commented on src/pages/signup.tsx
> +                          router.push(
I think the following is possible with the Next.JS router.

```
router.push({
    pathname: '/verify',
    query: { to: nextURL }
})
```

2021-07-15 16:46 UTC, legitmaxwu approved these changes
Looks good, nice work! Just a few more notes but then it should be good to merge!

2021-07-15 16:46 UTC, legitmaxwu commented on src/components/ProfileModal.tsx
> +  console.log(profile);
Remove

2021-07-15 16:46 UTC, legitmaxwu commented on src/components/ProfileModal.tsx
> +                          setStage(ProfileModalStage.BOOK_CHAT);
nit: Ternary might be a little confusing here. I'd just do 

```
if (authorizationLevel === AuthorizationLevel.Mentee) // book chat
```

2021-07-15 16:46 UTC, legitmaxwu commented on src/components/ProfileModal.tsx
> -                    disabled={authorizationLevel !== AuthorizationLevel.Mentee}
The button should be `disabled` for Admins

2021-07-15 20:42 UTC, merged