Fixed bug related to apollo cache operations overlapping
novaforgood/RISC-Frontend pull request #149
Opened 2021-08-02 21:07 UTC by innopoop

+ other auth page fixes

2021-08-02 21:53 UTC, legitmaxwu requested changes
Good stuff--only minor comments. Could you leave a more detailed description in the PR as to what exactly you fixed (or link the related Notion task or something)? There's not enough information for me to understand why this PR is necessary and what I should be looking out for during code review.

2021-08-02 21:53 UTC, legitmaxwu commented on src/components/Authentication/Signup.tsx
> +                console.log(loading);
remove console.log statement

2021-08-02 21:53 UTC, legitmaxwu commented on src/pages/signup.tsx
> -  if (
I'll assume this is deleted for the login page as well?

2021-08-02 21:59 UTC, nova-admin commented
#### 📝Changed routes:


| [**/login**](https://risc-2ukcvygh7-novaforgood.vercel.app/login) | [**/signup**](https://risc-2ukcvygh7-novaforgood.vercel.app/signup) |
|:-:|:-:|
|<a href="https://risc-2ukcvygh7-novaforgood.vercel.app/login"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/EQ2mdG2RipJDf-9zIlZQG6oQVVJ3_8jRj-R0foZ32PrlIK8dYxUbev9a0OCVjtGvtRlWMs7maX02L1fzfQUGiQ.png&w=600" alt="Screenshot of /login" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/a546Vr9hklbyveon-i6lvsjE-6qTcGDyFkNxlYs86aypmZhKT31u077xZAVKsZFUjrK3gZJqsziKOrpS9-wgvg.png">(view full size)</a> |<a href="https://risc-2ukcvygh7-novaforgood.vercel.app/signup"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/TbogYq6RMrpB5tySL0jq6UFRP1tlpEnyqUekJ-XIjkN0pZl6jm5EsGOXb0ZxHaOFqENozEPYfnEw66hCuVU7mA.png&w=600" alt="Screenshot of /signup" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/rrOuSJD56sH6U10_nmpnfN768SpNFzrmnuQ00Whwv1OQJVk2FDoX4tpOhyBBpilsybI8pQCWfjjv-hTN6ewTeg.png">(view full size)</a> |







Commit 58a527ef9e0a80348d53dc3c8dd6c325c6f40606 (https://risc-2ukcvygh7-novaforgood.vercel.app).

2021-08-03 11:41 UTC, legitmaxwu approved these changes

2021-08-03 11:41 UTC, legitmaxwu commented on src/pages/program/[slug]/index.tsx
> +  const [role, setRole] = useState<"mentor" | "mentee">("mentor");
Unnecessary state variable. just do

`const role = ...` instead

2021-08-03 11:54 UTC, merged