Form Compon
novaforgood/RISC-Frontend pull request #57
Opened 2021-06-12 23:03 UTC by hcsong213

## The feature is not ready yet
Just wanted to make a PR so that the code can be reviewed

2021-06-14 05:15 UTC, nova-admin commented
#### 📝Changed routes:


| [**/**](https://risc-4w7x5pm7e-novaforgood.vercel.app/) |
|:-:|
|<a href="https://risc-4w7x5pm7e-novaforgood.vercel.app/"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/dKHyWdTtI0JKpPcvJtmJe3U8mGqjM4QWXLrW_PeH6SX2evIOgJ3dbVTT321-WHAOylRjsEVSSGxqNfbdoVfWpg.png&w=600" alt="Screenshot of /" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/xMzZs35EeRx-wEm6XX4KkwFdqGdEOKPmz0jNMXYT-28G2QkIevYPW1iJtx_Il5qsdMu8PzZLCc7iYNFz_W0n2g.png">(view full size)</a> |







Commit 8da5d52b26f386dca3bd6de6941e6e5522da572b (https://risc-4w7x5pm7e-novaforgood.vercel.app).

2021-06-14 06:28 UTC, legitmaxwu requested changes
Questions

* Is there a way to prevent form clearing on submit? (Don't think we should clear the form on submit)
* Is there a way for me to detect whether the form has been modified from it's initial state? (Submit button is disabled until the first modification).

2021-06-14 06:28 UTC, legitmaxwu commented on src/components/Form.tsx
> +    <TitledInput
Might be better to use Text + Input instead of TitledInput because the title will be common across all questions

2021-06-14 06:28 UTC, legitmaxwu commented on src/components/Form.tsx
> +        {questions.map((q, i) => {
nit: `question` instead of `q` is slightly more readable imo

2021-06-14 06:28 UTC, legitmaxwu commented on src/components/Form.tsx
> +  }, 3000);
This interval could be passed in as a prop with default value=3000

2021-06-15 01:01 UTC, legitmaxwu commented on src/components/Form.tsx
> +  waitTime = 3000,
rename to `autosaveInterval`? `waitTime` seems a little general and the connection to `onAutosave` is not clear.

2021-06-15 01:24 UTC, legitmaxwu approved these changes

2021-06-15 04:52 UTC, merged