Set weekly availabilities
novaforgood/RISC-Frontend pull request #61
Opened 2021-06-15 07:34 UTC by kevinl120

2021-06-15 07:35 UTC, nova-admin commented
#### 📝Changed routes:


| [**…/\[slug\]/availabilities**](https://risc-qq9s3mfut-novaforgood.vercel.app/program/[slug]/availabilities) | [**/test/testcalendar**](https://risc-qq9s3mfut-novaforgood.vercel.app/test/testcalendar) |
|:-:|:-:|
|<a href="https://risc-qq9s3mfut-novaforgood.vercel.app/program/[slug]/availabilities"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/BbMaO0DwEDf7LFzl9KFOd07Ygqez3vC40LxszzBh7GfpsVx64kmj_PrmH6In3iAOWEQA8CYnoelREo8JR-KonQ.png&w=600" alt="Screenshot of /program/[slug]/availabilities" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/K3yADJcRrnU6snXS-TJPQ2vflDqj1a5MxJ0jiQI_96X2i1e1n4TyPiJ3uLlDRwb1F-GMkt3LrgNmFFrbsrATqA.png">(view full size)</a> |<a href="https://risc-qq9s3mfut-novaforgood.vercel.app/test/testcalendar"><img src="https://images.weserv.nl?url=https://sjc.microlink.io/0isuOQtgef34SALz9EzULustIEA0Lrt6aSQhsHlGFVeDOU5n5FTEN4qBhTFMWc3CdxeBI8Tac4MzCh4m2IVX4g.png&w=600" alt="Screenshot of /test/testcalendar" width="300"></a><br /><sup><a href="https://images.weserv.nl?url=https://sjc.microlink.io/OgKeD9fwh7IZSEeSan8TNxgkE2UgkgxRCKsAC_k8NqqtiZ2JB2vPbIahweJsaw91MempTkHAVleHXaNcHfzWkA.png">(view full size)</a> |







Commit 5d976c25b2a3014bd6d39c0dd105601b82454e04 (https://risc-qq9s3mfut-novaforgood.vercel.app).

2021-06-16 02:25 UTC, legitmaxwu requested changes

2021-06-16 02:25 UTC, legitmaxwu commented on codegen.yml
> +          content: "export type DateInterval = { startTime: Date, endTime: Date }"
I get that the generated file needs this type but maybe we could add an import path somehow, or configure a globals.ts file so it doesn't have to be imported

2021-06-16 02:25 UTC, legitmaxwu commented on src/components/atomic/Select.tsx
> +import {} from "lodash";
Whats's this line for?

2021-06-16 02:25 UTC, legitmaxwu commented on src/components/Availabilities/SetWeeklyAvailabilitiesCard.tsx
> +      return;
Throw/set an error indicator?

2021-06-16 08:27 UTC, legitmaxwu approved these changes

2021-06-16 08:27 UTC, merged